name: Deploy dotnet Application

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: publish
        run: dotnet publish -c Release -o public

      - name: Create public artifact
        uses: actions/upload-artifact@v3
        with:
          name: public_package
          path: public  

  deployment:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop iis
        run: iisreset /stop

      - name: Download the public folder
        uses: actions/download-artifact@v3
        with:
          name: public_package  

      - name: Copy public files to target directory
        run: copy .\public\* C:\inetpub\wwwroot\. -Force

      - name: Start iis
        run: iisreset /start


  uploadArtifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download the public folder
        uses: actions/download-artifact@v3
        with:
          name: public_package  
      - name: publish to artifactory
        run: |
          zip public.zip ./*
          curl -H ${{ secrets.JFROGKEY }} -T public.zip "https://gerardtorres.jfrog.io/artifactory/default-generic-local/package.zip"